# Site
name: "What is FORMULA 1?"
title: "What is FORMULA 1?"
description: "Learn about the fastest, most technologically advanced, motorsport in the world"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
include: ["_pages"]
permalink: /:title
collections_dir: collections

# Environment
environment: production

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
